.TH "MARKED\-MAN" "1" "May 2013" "" ""
.SH "NAME"
\fBmarked-man\fR \- markdown to roff
.SH SYNOPSIS
.P
.RS 2
.EX
marked\-man README\.md > doc/marked\-man\.1
.EE
.RE
.P
See marked README \fIhttps://github\.com/chjj/marked\fR for documentation
about how to use marked\.
.P
Note that \fBmarked\-man \-\-format=html\fR is the same as \fBmarked\fR\|\.
.SH DESCRIPTION
.P
\fBmarked\-man\fR wraps \fBmarked\fR to extend it with groff output support\.
.SH OPTIONS
.P
\fBmarked\-man\fR adds a some options to \fBmarked\fR existing options:
.RS 2
.IP \(bu 2
format
.br
Sets the output format\. Outputs html if different from \fBroff\fR\|\.
Defaults to \fBroff\fR\|\.
.IP \(bu 2
name
.br
The name shown in the manpage header, if it isn\'t given in the ronn
header like in this README\.
.br
Defaults to empty string\.
.IP \(bu 2
section
.br
The section shown in the manpage header, if it isn\'t given in the ronn
header like in this README\.
.br
Defaults to empty string\.
.IP \(bu 2
version
.br
The version shown in the manpage header\.
.br
Defaults to empty string\.
.IP \(bu 2
manual
.br
The MANUAL string shown in the manpage header\.
.br
Defaults to empty string\.
.IP \(bu 2
date
.br
The date shown in the manpage header\.
.br
Defaults to now, must be acceptable by new Date(string)\.

.RE
.SH REPORTING BUGS
.P
See marked\-man repository \fIhttps://github\.com/kapouer/marked\-man\fR\|\.
