.TH "T" "1" "January 1979"
.SH "NAME"
\fBt\fR \- test
.SH test
.RS 2
.nf
A blockquote here\.
Continuing on second line\.
.fi
.RE
.P
Hello\.
.TS
tab(|) nowarn;
cx.
T{
.P
Another block quote\. With a long title\. That will break a line eventually later\.
.br
that continues on second line
.br
continuation

T}
.TE
