.TH "" "" "November 2022" "" ""
.SH "NAME"
\fB\fRescapes tests
.P
backslashes before the asterisks, like this:
.RS 2
.nf
\\*literal asterisks\\*
.fi
.RE
.P
Markdown provides backslash escapes for the following characters:
.RS 2
.nf
\   backslash
`   backtick
*   asterisk
_   underscore
{}  curly braces
[]  square brackets
()  parentheses
#   hash mark
+   plus sign
-   minus sign (hyphen)
\|.   dot
!   exclamation mark
.fi
.RE

