.TH "ESCAPES" "1" "January 1979"
.SH "NAME"
\fBescapes\fR
.P
backslashes before the asterisks, like this:
.RS 2
.nf
\\*literal asterisks\\*
.fi
.RE
.P
Markdown provides backslash escapes for the following characters:
.RS 2
.nf
\\   backslash
`   backtick
*   asterisk
_   underscore
{}  curly braces
[]  square brackets
()  parentheses
#   hash mark
+   plus sign
\-   minus sign (hyphen)
\|\.   dot
!   exclamation mark
.fi
.RE
