.TH "LINKS" "1" "January 1979"
.SH "NAME"
\fBlinks\fR
.P
I get 10 times more traffic from 
.UR http://google.com/
.I Google
.UE
than from
.br
.UR http://search.yahoo.com/
.I Yahoo Search
.UE
or 
.UR http://search.msn.com/
.I MSN Search
.UE .
.P
This is to test proper escape of html chars and non\-repeating link:
.br
xxxxx@xxxx.xxxx.xxxx.xx
.P
I get 10 times more traffic from 
.UR http://google.com/
.I Google
.UE
than from
.br
.UR http://search.yahoo.com/
.I Yahoo Search
.UE
or 
.UR http://search.msn.com/
.I MSN Search
.UE .
.P
Non\-repeating http link https://example.com/test
.P
Also
.br
.UR http://google.com/
.I Google
.UE
.P
and 
.UR ./table.md
.I local links should not crash
.UE
