.TH "A" "1" "January 1979"
.SH "NAME"
\fBa\fR
.P
This is a tight list:

.RS 1
.IP \(bu 2
\fBtoggle_status\fP: test
.IP \(bu 2
\fBspawn <executable> <additional args>\fP
.br
TODO explain path\-alike expansion,
.br
ability to get a block here\.

.RE
.P
This is a loose list:

.RS 1
.IP \(bu 2
\fBtoggle_status\fP:
.br
test
.IP \(bu 2
\fBspawn <executable> <additional args>\fP:
.br
TODO explain path\-alike expansion,
.br
ability to get a block here\.

.RE
