.TH "A" "1" "January 1979"
.SH "NAME"
\fBa\fR
.P
Tight list:

.RS 1
.IP \(bu 2
\fBtoggle_status\fP
.RS 1
.IP \(bu 2
Toggle the display of the status bar1
.IP \(bu 2
Toggle the display of the status bar2

.RE
.IP \(bu 2
\fBspawn <executable> <additional args>\fP TODO explain path\-alike expansion

.RE
.P
Loose list:

.RS 1
.IP \(bu 2
\fBtoggle_status\fP

.RS 1
.IP \(bu 2
Toggle the display of the status bar1
.IP \(bu 2
Toggle the display of the status bar2

.RE
.IP \(bu 2
\fBspawn <executable> <additional args>\fP TODO explain path\-alike expansion

.RE
