.TH "TABLE" "7" "January 1979"
.SH "NAME"
\fBtable\fR \- test data for table format
.P
test table copy and paste form www\.
.SH LARGE TABLE
.P
.UR https://en.wikipedia.org/wiki/Comparison_of_file_systems
.I Comparison of file systems
.UE
.TS
tab(|) expand nowarn box;
l l l l.
T{
File system
T}|T{
Creator
T}|T{
Year of introduction
T}|T{
Original operating system
T}
=
T{
DECtape
T}|T{
DEC
T}|T{
1964
T}|T{
PDP\-6 Monitor
T}
_
T{
DASD
T}|T{
IBM
T}|T{
1964
T}|T{
OS/360
T}
_
T{
Level\-D
T}|T{
DEC
T}|T{
1968
T}|T{
TOPS\-10
T}
_
T{
George 2
T}|T{
ICT (later ICL)
T}|T{
1968
T}|T{
George 2
T}
_
T{
Version 6 Unix file system (V6FS)
T}|T{
Bell Labs
T}|T{
1972
T}|T{
Version 6 Unix
T}
_
T{
RT\-11 file system
T}|T{
DEC
T}|T{
1973
T}|T{
RT\-11
T}
_
T{
Disk Operating System (GEC DOS)
T}|T{
GEC
T}|T{
1973
T}|T{
Core Operating System
T}
_
T{
CP/M file system
T}|T{
Digital Research (Gary Kildall)
T}|T{
1974
T}|T{
CP/M[1]
T}
_
T{
ODS\-1
T}|T{
DEC
T}|T{
1975
T}|T{
RSX\-11
T}
_
T{
GEC DOS filing system extended
T}|T{
GEC
T}|T{
1977
T}|T{
OS4000
T}
_
T{
FAT (8\-bit)
T}|T{
Microsoft (Marc McDonald) for NCR
T}|T{
1977
T}|T{
Microsoft Standalone Disk BASIC\-80 (later Microsoft Standalone Disk BASIC\-86)
T}
_
T{
DOS 3\.x
T}|T{
Apple Computer
T}|T{
1978
T}|T{
Apple DOS
T}
_
T{
Pascal
T}|T{
Apple Computer
T}|T{
1978
T}|T{
Apple Pascal
T}
_
T{
CBM DOS
T}|T{
Commodore
T}|T{
1978
T}|T{
Commodore BASIC
T}
_
T{
Version 7 Unix file system (V7FS)
T}|T{
Bell Labs
T}|T{
1979
T}|T{
Version 7 Unix
T}
_
T{
ODS\-2
T}|T{
DEC
T}|T{
1979
T}|T{
OpenVMS
T}
.TE
.SH LONG TEXT
.TS
tab(|) expand nowarn box;
l l l.
T{
Person
T}|T{
Work
T}|T{
Quote
T}
=
T{
Sherlock Holmes
T}|T{
The Norwood Builder
T}|T{
You mentioned your name as if I should recognize it, but beyond the obvious facts that you are a bachelor, a solicitor, a freemason, and an asthmatic, I know nothing whatever about you\.
T}
.TE
.SH THING TABLE
.TS
tab(|) expand nowarn box;
l l.
T{
1
T}|T{
2
T}
=
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
T{1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
.TE
