.TH "TABLE" "7" "January 1979" "" ""
.SH "NAME"
\fBtable\fR \- test data for table format
.P
test table copy and paste form www\. 
.SH LARGE TABLE
.P
https://en\.wikipedia\.org/wiki/Comparison_of_file_systems
.TS
tab(|) expand nowarn box;
 l l l l.
T{
File system
T}|T{
Creator
T}|T{
Year of introduction
T}|T{
Original operating system
T}
_
T{
DECtape
T}|T{
DEC
T}|T{
1964
T}|T{
PDP\-6 Monitor
T}
T{
DASD
T}|T{
IBM
T}|T{
1964
T}|T{
OS/360
T}
T{
Level\-D
T}|T{
DEC
T}|T{
1968
T}|T{
TOPS\-10
T}
T{
George 2
T}|T{
ICT (later ICL)
T}|T{
1968
T}|T{
George 2
T}
T{
Version 6 Unix file system (V6FS)
T}|T{
Bell Labs
T}|T{
1972
T}|T{
Version 6 Unix
T}
T{
RT\-11 file system
T}|T{
DEC
T}|T{
1973
T}|T{
RT\-11
T}
T{
Disk Operating System (GEC DOS)
T}|T{
GEC
T}|T{
1973
T}|T{
Core Operating System
T}
T{
CP/M file system
T}|T{
Digital Research (Gary Kildall)
T}|T{
1974
T}|T{
CP/M[1][2]
T}
T{
ODS\-1
T}|T{
DEC
T}|T{
1975
T}|T{
RSX\-11
T}
T{
GEC DOS filing system extended
T}|T{
GEC
T}|T{
1977
T}|T{
OS4000
T}
T{
FAT (8\-bit)
T}|T{
Microsoft (Marc McDonald) for NCR
T}|T{
1977
T}|T{
Microsoft Standalone Disk BASIC\-80 (later Microsoft Standalone Disk BASIC\-86)
T}
T{
DOS 3\.x
T}|T{
Apple Computer
T}|T{
1978
T}|T{
Apple DOS
T}
T{
Pascal
T}|T{
Apple Computer
T}|T{
1978
T}|T{
Apple Pascal
T}
T{
CBM DOS
T}|T{
Commodore
T}|T{
1978
T}|T{
Commodore BASIC
T}
T{
Version 7 Unix file system (V7FS)
T}|T{
Bell Labs
T}|T{
1979
T}|T{
Version 7 Unix
T}
T{
ODS\-2
T}|T{
DEC
T}|T{
1979
T}|T{
OpenVMS
T}
T{
FAT12
T}|T{
Seattle Computer Products (Tim Paterson)
T}|T{
1980
T}|T{
QDOS/86\-DOS (later IBM PC DOS 1\.0)
T}
T{
DFS
T}|T{
Acorn Computers Ltd
T}|T{
1982
T}|T{
Acorn BBC Micro MOS
T}
T{
ADFS
T}|T{
Acorn Computers Ltd
T}|T{
1983
T}|T{
Acorn Electron (later Arthur RISC OS)
T}
T{
FFS
T}|T{
Kirk McKusick
T}|T{
1983
T}|T{
4\.2BSD
T}
T{
ProDOS
T}|T{
Apple Computer
T}|T{
1983
T}|T{
ProDOS 8
T}
T{
FAT16
T}|T{
IBM, Microsoft
T}|T{
1984
T}|T{
PC DOS 3\.0, MS\-DOS 3\.0
T}
T{
MFS
T}|T{
Apple Computer
T}|T{
1984
T}|T{
System 1
T}
T{
Elektronika BK tape format
T}|T{
NPO "Scientific centre" (now Sitronics)
T}|T{
1985
T}|T{
Vilnius Basic, BK monitor program
T}
T{
HFS
T}|T{
Apple Computer
T}|T{
1985
T}|T{
System 2\.1
T}
T{
Amiga OFS[1]
T}|T{
Metacomco for Commodore
T}|T{
1985
T}|T{
Amiga OS
T}
T{
NWFS
T}|T{
Novell
T}|T{
1985
T}|T{
NetWare 286
T}
T{
High Sierra
T}|T{
Ecma International
T}|T{
1986
T}|T{
MSCDEX for MS\-DOS 3\.1/3\.2[3]
T}
T{
FAT16B
T}|T{
Compaq
T}|T{
1987
T}|T{
Compaq MS\-DOS 3\.31
T}
T{
Minix V1 FS
T}|T{
Andrew S\. Tanenbaum
T}|T{
1987
T}|T{
MINIX 1\.0
T}
T{
Amiga FFS
T}|T{
Commodore
T}|T{
1988
T}|T{
Amiga OS 1\.3
T}
T{
ISO 9660:1988
T}|T{
Ecma International, ISO
T}|T{
1988
T}|T{
MS\-DOS, "classic" Mac OS, and AmigaOS
T}
T{
HPFS
T}|T{
IBM & Microsoft
T}|T{
1989
T}|T{
OS/2 1\.2
T}
T{
JFS1
T}|T{
IBM
T}|T{
1990
T}|T{
AIX[a]
T}
T{
VxFS
T}|T{
VERITAS
T}|T{
1991
T}|T{
SVR4\.0
T}
T{
ext
T}|T{
Rémy Card
T}|T{
1992
T}|T{
Linux
T}
T{
AdvFS
T}|T{
DEC
T}|T{
1993[4]
T}|T{
Digital Unix
T}
T{
NTFS
T}|T{
Microsoft (Gary Kimura, Tom Miller)
T}|T{
1993
T}|T{
Windows NT 3\.1
T}
T{
LFS
T}|T{
Margo Seltzer
T}|T{
1993
T}|T{
Berkeley Sprite
T}
T{
ext2
T}|T{
Rémy Card
T}|T{
1993
T}|T{
Linux, Hurd
T}
T{
Xiafs
T}|T{
Q\. Frank Xia
T}|T{
1993
T}|T{
Linux
T}
T{
UFS1
T}|T{
Kirk McKusick
T}|T{
1994
T}|T{
4\.4BSD
T}
T{
XFS
T}|T{
SGI
T}|T{
1994
T}|T{
IRIX, Linux, FreeBSD
T}
T{
HFS
T}|T{
IBM
T}|T{
1994
T}|T{
MVS/ESA (now z/OS)
T}
T{
FAT16X
T}|T{
Microsoft
T}|T{
1995
T}|T{
MS\-DOS 7\.0 / Windows 95
T}
T{
Joliet ("CDFS")
T}|T{
Microsoft
T}|T{
1995
T}|T{
Microsoft Windows, Linux, "classic" Mac OS, and FreeBSD
T}
T{
UDF
T}|T{
ISO/ECMA/OSTA
T}|T{
1995
T}|T{
N/A
T}
T{
FAT32, FAT32X
T}|T{
Microsoft
T}|T{
1996
T}|T{
MS\-DOS 7\.10 / Windows 95 OSR2[b]
T}
T{
QFS
T}|T{
Sun Microsystems
T}|T{
1996
T}|T{
Solaris
T}
T{
GPFS
T}|T{
IBM
T}|T{
1996
T}|T{
AIX, Linux
T}
T{
Be File System
T}|T{
Be Inc\. (D\. Giampaolo, Cyril Meurillon)
T}|T{
1996
T}|T{
BeOS
T}
T{
Minix V2 FS
T}|T{
Andrew S\. Tanenbaum
T}|T{
1997
T}|T{
MINIX 2\.0
T}
T{
HFS Plus
T}|T{
Apple Computer
T}|T{
1998
T}|T{
Mac OS 8\.1
T}
T{
NSS
T}|T{
Novell
T}|T{
1998
T}|T{
NetWare 5
T}
T{
PolyServe File System (PSFS)
T}|T{
PolyServe
T}|T{
1998
T}|T{
Windows, Linux
T}
T{
ODS\-5
T}|T{
DEC
T}|T{
1998
T}|T{
OpenVMS 7\.2
T}
T{
WAFL
T}|T{
NetApp
T}|T{
1998
T}|T{
Data ONTAP
T}
T{
ext3
T}|T{
Dr\. Stephen C\. Tweedie
T}|T{
1999
T}|T{
Linux
T}
T{
ISO 9660:1999
T}|T{
Ecma International, ISO
T}|T{
1999
T}|T{
Microsoft Windows, Linux, "classic" Mac OS, FreeBSD, and AmigaOS
T}
T{
Lustre
T}|T{
Cluster File Systems[5]
T}|T{
2002
T}|T{
Linux
T}
T{
JFS
T}|T{
IBM
T}|T{
1999
T}|T{
OS/2 Warp Server for e\-business
T}
T{
GFS
T}|T{
Sistina (Red Hat)
T}|T{
2000
T}|T{
Linux
T}
T{
ReiserFS
T}|T{
Namesys
T}|T{
2001
T}|T{
Linux
T}
T{
zFS
T}|T{
IBM
T}|T{
2001
T}|T{
z/OS (backported to OS/390)
T}
T{
FATX
T}|T{
Microsoft
T}|T{
2002
T}|T{
Xbox
T}
T{
UFS2
T}|T{
Kirk McKusick
T}|T{
2002
T}|T{
FreeBSD 5\.0
T}
T{
OCFS
T}|T{
Oracle Corporation
T}|T{
2002
T}|T{
Linux
T}
T{
VMFS2
T}|T{
VMware
T}|T{
2002
T}|T{
VMware ESX Server 2\.0
T}
T{
Fossil
T}|T{
Bell Labs
T}|T{
2003
T}|T{
Plan 9 version 4
T}
T{
Google File System
T}|T{
Google
T}|T{
2003
T}|T{
Linux
T}
T{
ZFS
T}|T{
Sun Microsystems
T}|T{
2004
T}|T{
Solaris
T}
T{
Reiser4
T}|T{
Namesys
T}|T{
2004
T}|T{
Linux
T}
T{
Non\-Volatile File System
T}|T{
Palm, Inc\.
T}|T{
2004
T}|T{
Palm OS Garnet
T}
T{
Minix V3 FS
T}|T{
Andrew S\. Tanenbaum
T}|T{
2005
T}|T{
MINIX 3
T}
T{
OCFS2
T}|T{
Oracle Corporation
T}|T{
2005
T}|T{
Linux
T}
T{
NILFS
T}|T{
NTT
T}|T{
2005
T}|T{
Linux
T}
T{
VMFS3
T}|T{
VMware
T}|T{
2005
T}|T{
VMware ESX Server 3\.0
T}
T{
GFS2
T}|T{
Red Hat
T}|T{
2006
T}|T{
Linux
T}
T{
ext4
T}|T{
various
T}|T{
2006
T}|T{
Linux
T}
T{
exFAT
T}|T{
Microsoft
T}|T{
2006
T}|T{
Windows CE 6\.0
T}
T{
Btrfs
T}|T{
Oracle Corporation
T}|T{
2007
T}|T{
Linux
T}
T{
JXFS
T}|T{
Hyperion Entertainment
T}|T{
2008
T}|T{
AmigaOS 4\.1
T}
T{
HAMMER
T}|T{
Matthew Dillon
T}|T{
2008
T}|T{
DragonFly BSD 2\.0
T}
T{
LSFS
T}|T{
StarWind Software
T}|T{
2009
T}|T{
Linux, FreeBSD, Windows
T}
T{
CASL
T}|T{
Nimble Storage
T}|T{
2010
T}|T{
Linux
T}
T{
VMFS5
T}|T{
VMware
T}|T{
2011
T}|T{
vSphere 5\.0+
T}
T{
ReFS
T}|T{
Microsoft
T}|T{
2012
T}|T{
Windows Server 2012
T}
T{
F2FS
T}|T{
Samsung Electronics
T}|T{
2012
T}|T{
Linux
T}
T{
APFS
T}|T{
Apple Computer
T}|T{
2016
T}|T{
macOS
T}
.TE
.SH LONG TEXT
.P
http://www\.troff\.org/faq\.html
.TS
tab(|) expand nowarn box;
 l l l.
T{
Person
T}|T{
Work
T}|T{
Quote
T}
_
T{
Sherlock Holmes
T}|T{
The Norwood Builder
T}|T{
You mentioned your name as if I should recognize it, but beyond the obvious facts that you are a bachelor, a solicitor, a freemason, and an asthmatic, I know nothing whatever about you\.
T}
.TE
.SH THING TABLE
.TS
tab(|) expand nowarn box;
 l l.
T{
1
T}|T{
2
T}
_
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
T{1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
T{
1
T}|T{
2
T}
.TE
.SH REPORTING BUGS
.P
xxxxx@xxxx\.xxxx\.xxxx\.xx
